### ISSUE TITLE
Cannot connect to CLion

### ISSUE THREAD

**Issue by vastsoun** [CoatiSoftware/idea-sourcetrail#1]
Hi,

**Setup:**
Ubuntu 16.04LTS
CLion 2017.2.3
Sourcetrail 2107.3.48

**Description:**
I have a large CMake project (lots of dependent CMake modules/projects). Following the instructions, I created the respective Sourcetrail project using the .json compilation database and the indexing mostly worked (it works but a few files were not indexed for unrelated reasons). I cannot, however, get CLion to talk to Sourcetrail. 

I have my clion project dir consisting of a `src/` directory with symlinks to all the CMake sub-projects and a  main CMakeLists.txt which includes all other modules using `add_subdirectory()` commands. The main CMakeLists.txt was used to generate the single `compile_commands.json` which was the used to generate the respective Sourcetrail project.

**Sourcetrail error message:**
```
Activating source location from plug-in failed. File "/home/vassilis/path/to/existing/file" was not found in the project.
```

**CLion error message:**
```
com/intellij/openapi/actionSystem/DataKeys
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/DataKeys
	at io.sourcetrail.idea.ActivateTokenAction.actionPerformed(ActivateTokenAction.java:61)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.actionSystem.DataKeys PluginClassLoader[io.sourcetrail.idea, 0.4.6] com.intellij.ide.plugins.cl.PluginClassLoader@7489993c
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 51 more
```

**Comment by mlangkabel** [comment]
Hi @vastsoun, thanks for opening this issue. It looks like you managed to two problems at once! 

The __Sourcetrail error message__ looks like Sourcetrail cannot match the file name CLion provides to any file it has indexed. Can you please try to find and activate that file from within Sourcetrail using the search bar, and hover the file title in the code view? The tooltip shows you the file path Sourcetrail uses to reference this file. This path probably differs from the path in your error message. Can you check what the difference is?

The __CLion error message__ is something we can reproduce even if the synchronization between Sourcetrail and CLion is working, so we should be able to fix that. I'll keep you updated on our progress!

**Comment by mlangkabel** [comment]
Status update: We investigated the issue regarding the Sourcetrail error message further and it appears that this is an issue with all our Sourcetrail IDE plugins. We were able to reproduce this even for the Visual Studio extension. I'll keep you up to date, once we have a fix for this in place.

**Comment by mlangkabel** [comment]
The issue related to the Sourcetrail error message has been fixed by now. This fix will be part of our next release.

**Comment by vastsoun** [comment]
Hi,

Unfortunately I tested the latest version and I still get the issue. I know what the problem is however, and it has to do with my setup/workflow:

1. Code is actually stored in a central `git/` dir where I place all my repos.
2. CLion project exists in special dir with other CLion projects, and source is symlinked into these. Th CMake build step (in CLion) which generates the the `compile_commands.json` file outputs the relative commands that CLion sees.
3. When I create the Sourcetrail project, the tool seems to resolve the absolute paths of all the files and hence fails to recognize the ones emmited by the CLion plugin.

Thus I would guess that the issue lies mainly with the plugin.

**Comment by mlangkabel** [comment]
@vastsoun: Do you refer to Sourcetrail 2017.4.20 when you say "latest version"? With this release we tried to fix this issue from the Sourcetrail side by making file each path that Sourcetrail receives via plugin canonical (which means that we resolve the symlinks) before actually using the path.

Can you please tell me if the path that Sourcetrail displays in the status bar (when telling you that it couldn't activate a source location) is the canonical path (pointing inside your `git/` folder where the code is actually stored) or the path containing the symlink?

**Comment by mlangkabel** [comment]
CLion error message is now fixed as well.
